import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Form from "../components/Form";
import { NotificationsProvider } from "@mantine/notifications";
import {
  MantineProvider,
  ColorSchemeProvider,
  Container,
  Box,
} from "@mantine/core";
import { useMantineTheme } from "@mantine/core";

export default function Home() {
  const theme = useMantineTheme();
  const [colorScheme, setColorScheme] = React.useState("light");
  const toggleColorScheme = (value) =>
    setColorScheme(value || (colorScheme === "dark" ? "light" : "dark"));
  return (
    <ColorSchemeProvider
      colorScheme={colorScheme}
      toggleColorScheme={toggleColorScheme}
    >
      <MantineProvider theme={{ colorScheme }}>
        <NotificationsProvider>
          <Container
            className={styles.container}
            sx={(theme) => ({
              backgroundColor:
                theme.colorScheme === "dark"
                  ? theme.colors.dark[5]
                  : theme.colors.gray[0],
            })}
          >
            <Head>
              <title>RFC Form Portal</title>
              <meta name="description" content="Generated by Eirik" />
              <link rel="icon" href="/favicon.ico" />
            </Head>

            <Box className={styles.main}>
              <Form />
            </Box>

            <footer className={styles.footer}>
              <Container>
                <a
                  href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Powered by{" "}
                  <span className={styles.logo}>
                    <Image
                      src="/vercel.svg"
                      alt="Vercel Logo"
                      width={72}
                      height={16}
                    />
                  </span>
                </a>
              </Container>
            </footer>
          </Container>
        </NotificationsProvider>
      </MantineProvider>
    </ColorSchemeProvider>
  );
}
